name: greet

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/zp-tool-config
          path: config
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-python@main
        with:
          python-version: 3.13
      - run: |
          sudo apt-get update && sudo apt-get install -y age chromium-browser xvfb
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install -r requirements.txt --upgrade
          mkdir --parents .config/age
          echo '${{ secrets.AGE_SECRET_KEY }}' > .config/age/key.txt
          age --decrypt --identity .config/age/key.txt --output .env config/.env.age
          age --decrypt --identity .config/age/key.txt --output config.yaml config/config.yaml.age
          age --decrypt --identity .config/age/key.txt --output models.py config/models.py.age
          age --decrypt --identity .config/age/key.txt --output cookies.json config/cookies.json.age
          set -a
          source .env
          source .venv/bin/activate
          set +a
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          python app.py ++task=greet
